import sbt._
import scalapb.compiler.Version.scalapbVersion

object Libs {
  val ScalaVersion = "2.13.0"
  val `jgroup` = "org.jgroups" % "jgroups" % "4.0.0.Final"
  val `zookeeper` =  "org.apache.zookeeper" % "zookeeper" % "3.5.5"
  val `zkclient` = "com.101tec" % "zkclient" % "0.11"
  val `yammer` = "com.yammer.metrics" % "metrics-core" % "2.2.0"
  val `scalaLogging` = "com.typesafe.scala-logging" %% "scala-logging" % "3.9.2"
  val `jacksonDatabind` =  "com.fasterxml.jackson.core" % "jackson-databind" % "2.9.9.3"
  val `jacksonDataformatCsv` =  "com.fasterxml.jackson.dataformat" % "jackson-dataformat-csv" % "2.9.9"
  val `jacksonModuleScala` =  "com.fasterxml.jackson.module" %% "jackson-module-scala" % "2.9.9"
  val `jacksonJDK8Datatypes` =  "com.fasterxml.jackson.datatype" % "jackson-datatype-jdk8" % "2.9.9"
  val `jacksonJaxrsJsonProvider` = "com.fasterxml.jackson.jaxrs" % "jackson-jaxrs-json-provider" % "2.9.9"
  val `scalaCollectionCompat` = "org.scala-lang.modules" %% "scala-collection-compat" % "2.1.2"
  val `scalaTest` = "org.scalatest" %% "scalatest" % "3.0.8"
  val `googleGuava` = "com.google.guava" % "guava" % "23.0"
  val `jamm` = "com.github.jbellis" % "jamm" % "0.3.3"
  val `mockito` = "org.mockito" %% "mockito-scala" % "1.5.16"
  val `pcj` = "pcj" % "pcj" % "1.2"
  val `akka-stream-typed` = "com.typesafe.akka" %% "akka-stream-typed" % "2.6.1"
  val `commons-codec` = "commons-codec" % "commons-codec" % "1.9"
  val `disruptor` = "com.lmax" % "disruptor" % "3.4.2"
  val `junit` = "junit" % "junit" % "4.13"
  val `jmh-core` = "org.openjdk.jmh" % "jmh-core" % "1.19"
  val `jmh_bench` = "org.openjdk.jmh" % "jmh-java-benchmark-archetype" % "1.19"
  val `jmh_generator_ann` = "org.openjdk.jmh" % "jmh-generator-annprocess" % "1.19"
  val `jmh_generator_bytecode` = "org.openjdk.jmh" % "jmh-generator-bytecode" % "1.19"
  val `jna` = "net.java.dev.jna" % "jna" % "4.2.2"
  val `yammer-core` = "net.java.dev.jna" % "jna" % "4.2.2"
  val `commons-lang` = "org.apache.commons" % "commons-lang3" % "3.6"
  val `commons-collections4` = "org.apache.commons" % "commons-collections4" % "4.1"
  val `commons-cli` = "commons-cli" % "commons-cli" % "1.2"
  val `rocksdb` = "org.rocksdb" % "rocksdbjni" % "5.13.1"
}
