// Code generated by protoc-gen-go. DO NOT EDIT.
// source: append_entries_responses.proto

package raftpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AppendEntriesResponse struct {
	Term                 *uint64  `protobuf:"varint,1,req,name=Term" json:"Term,omitempty"`
	Index                *uint64  `protobuf:"varint,2,req,name=Index" json:"Index,omitempty"`
	CommitIndex          *uint64  `protobuf:"varint,3,req,name=CommitIndex" json:"CommitIndex,omitempty"`
	Success              *bool    `protobuf:"varint,4,req,name=Success" json:"Success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppendEntriesResponse) Reset()         { *m = AppendEntriesResponse{} }
func (m *AppendEntriesResponse) String() string { return proto.CompactTextString(m) }
func (*AppendEntriesResponse) ProtoMessage()    {}
func (*AppendEntriesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a368336dcc979e3, []int{0}
}

func (m *AppendEntriesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendEntriesResponse.Unmarshal(m, b)
}
func (m *AppendEntriesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendEntriesResponse.Marshal(b, m, deterministic)
}
func (m *AppendEntriesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendEntriesResponse.Merge(m, src)
}
func (m *AppendEntriesResponse) XXX_Size() int {
	return xxx_messageInfo_AppendEntriesResponse.Size(m)
}
func (m *AppendEntriesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendEntriesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AppendEntriesResponse proto.InternalMessageInfo

func (m *AppendEntriesResponse) GetTerm() uint64 {
	if m != nil && m.Term != nil {
		return *m.Term
	}
	return 0
}

func (m *AppendEntriesResponse) GetIndex() uint64 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func (m *AppendEntriesResponse) GetCommitIndex() uint64 {
	if m != nil && m.CommitIndex != nil {
		return *m.CommitIndex
	}
	return 0
}

func (m *AppendEntriesResponse) GetSuccess() bool {
	if m != nil && m.Success != nil {
		return *m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*AppendEntriesResponse)(nil), "raftpb.AppendEntriesResponse")
}

func init() { proto.RegisterFile("append_entries_responses.proto", fileDescriptor_8a368336dcc979e3) }

var fileDescriptor_8a368336dcc979e3 = []byte{
	// 134 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4b, 0x2c, 0x28, 0x48,
	0xcd, 0x4b, 0x89, 0x4f, 0xcd, 0x2b, 0x29, 0xca, 0x4c, 0x2d, 0x8e, 0x2f, 0x4a, 0x2d, 0x2e, 0xc8,
	0xcf, 0x2b, 0x4e, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2b, 0x4a, 0x4c, 0x2b,
	0x29, 0x48, 0x52, 0x8a, 0xe2, 0x12, 0x75, 0x04, 0xab, 0x74, 0x85, 0x28, 0x0c, 0x82, 0xaa, 0x13,
	0xe2, 0xe1, 0x62, 0x09, 0x49, 0x2d, 0xca, 0x95, 0x60, 0x54, 0x60, 0xd2, 0x60, 0x11, 0xe2, 0xe5,
	0x62, 0xf5, 0xcc, 0x4b, 0x49, 0xad, 0x90, 0x60, 0x02, 0x73, 0x85, 0xb9, 0xb8, 0x9d, 0xf3, 0x73,
	0x73, 0x33, 0x4b, 0x20, 0x82, 0xcc, 0x60, 0x41, 0x7e, 0x2e, 0xf6, 0xe0, 0xd2, 0xe4, 0xe4, 0xd4,
	0xe2, 0x62, 0x09, 0x16, 0x05, 0x26, 0x0d, 0x0e, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4f, 0x75,
	0x35, 0x95, 0x84, 0x00, 0x00, 0x00,
}
