// Code generated by protoc-gen-go. DO NOT EDIT.
// source: request_vote_responses.proto

package raftpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestVoteResponse struct {
	Term                 *uint64  `protobuf:"varint,1,req,name=Term" json:"Term,omitempty"`
	VoteGranted          *bool    `protobuf:"varint,2,req,name=VoteGranted" json:"VoteGranted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestVoteResponse) Reset()         { *m = RequestVoteResponse{} }
func (m *RequestVoteResponse) String() string { return proto.CompactTextString(m) }
func (*RequestVoteResponse) ProtoMessage()    {}
func (*RequestVoteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_933349f1f1020bc9, []int{0}
}

func (m *RequestVoteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestVoteResponse.Unmarshal(m, b)
}
func (m *RequestVoteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestVoteResponse.Marshal(b, m, deterministic)
}
func (m *RequestVoteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestVoteResponse.Merge(m, src)
}
func (m *RequestVoteResponse) XXX_Size() int {
	return xxx_messageInfo_RequestVoteResponse.Size(m)
}
func (m *RequestVoteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestVoteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RequestVoteResponse proto.InternalMessageInfo

func (m *RequestVoteResponse) GetTerm() uint64 {
	if m != nil && m.Term != nil {
		return *m.Term
	}
	return 0
}

func (m *RequestVoteResponse) GetVoteGranted() bool {
	if m != nil && m.VoteGranted != nil {
		return *m.VoteGranted
	}
	return false
}

func init() {
	proto.RegisterType((*RequestVoteResponse)(nil), "raftpb.RequestVoteResponse")
}

func init() { proto.RegisterFile("request_vote_responses.proto", fileDescriptor_933349f1f1020bc9) }

var fileDescriptor_933349f1f1020bc9 = []byte{
	// 109 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x29, 0x4a, 0x2d, 0x2c,
	0x4d, 0x2d, 0x2e, 0x89, 0x2f, 0xcb, 0x2f, 0x49, 0x8d, 0x2f, 0x4a, 0x2d, 0x2e, 0xc8, 0xcf, 0x2b,
	0x4e, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2b, 0x4a, 0x4c, 0x2b, 0x29, 0x48,
	0x52, 0xb2, 0xe0, 0x12, 0x0e, 0x82, 0xa8, 0x0b, 0xcb, 0x2f, 0x49, 0x0d, 0x82, 0xaa, 0x12, 0xe2,
	0xe1, 0x62, 0x09, 0x49, 0x2d, 0xca, 0x95, 0x60, 0x54, 0x60, 0xd2, 0x60, 0x11, 0x12, 0xe6, 0xe2,
	0x06, 0xc9, 0xba, 0x17, 0x25, 0xe6, 0x95, 0xa4, 0xa6, 0x48, 0x30, 0x29, 0x30, 0x69, 0x70, 0x00,
	0x02, 0x00, 0x00, 0xff, 0xff, 0xc6, 0x4a, 0x4a, 0xaf, 0x60, 0x00, 0x00, 0x00,
}
